# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 23:45
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20170414_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_transaction',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=8),
            preserve_default=False,
        ),
    ]
