# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_stock_transaction_my_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_transaction',
            old_name='my_field',
            new_name='Type',
        ),
    ]
