# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_auto_20170414_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_record',
            name='Date_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_transaction',
            name='Date_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
