# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_auto_20170415_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_transaction',
            name='Balance_at_Time',
            field=models.FloatField(default=338.0),
            preserve_default=False,
        ),
    ]
